language: java
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

branches:
  only:
  - master

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY_API
  app: groovy-dsl

addons:
  sonarcloud:
  token:
    secure: $SONAR_TOKEN
  script:
    - ./gradlew sonarqube